Repository hmcts/send-letter-service-container-zip, pull requests merged in 2022-04, with the labels that each got.

#95 Suppress vulneribilities and upgrade dependency-check version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-zip-pr-95

#108 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-zip-pr-108

#112 Suppressed CVE-2022-22968
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-zip-pr-112
